version: "3"
services:
  frontend:
    image: ghcr.io/int222-integrated-project/int222-front-end:master
    container_name: frontend
    networks:
       int222:
          ipv4_address: 172.10.0.2
networks:
  default:
    external:
       name: int222
  int222:
    external: true