name: font-end CICD

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
          login-server: ghcr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

  deploy:
    needs:
      - build
    runs-on: ubuntu-20.04
    steps:
    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATEKEY }}
        port: ${{ secrets.SERVERPORT }}
        script: | 
          cd /
          sudo docker-compose down && sudo docker-compose pull
          sudo docker-compose up -d
          sudo docker image prune -af
    