name: back-end
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATEKEY }}
        port: ${{ secrets.SERVERPORT }}
        script:  
          cd ./frontend 
          docker-compose down && docker-compose pull &&
          docker-compose up -d &&
          docker image prune -af
